(source melpa)
(source marmalade)

(depends-on "cask")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "grizzl")
(depends-on "hemisu-theme")
(depends-on "sublime-themes")
(depends-on "surround")
(depends-on "projectile")
