#+TITLE: navigation

* Navigating around

** Projectile

[[https://github.com/bbatsov/projectile][Projectile]] is a brilliant project
interaction library for Emacs. Navigate around files, buffers, recently opened
files etc. Some of Projectile's features:

#+BEGIN_QUOTE
  * jump to a file in project
  * jump to a directory in project
  * jump to a file in a directory
  * jump to a project buffer
  * jump to a test in project
  * toggle between code and its test
  * jump to recently visited files in the project
  * switch between projects you have worked on
  * kill all project buffers
  * replace in project
  * multi-occur in project buffers
  * grep in project
  * regenerate project etags or gtags (requires gtags).
  * visit project in dired
  * run make in a project with a single key chord

  -- https://github.com/bbatsov/projectile
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(use-package projectile
  :diminish projectile-mode
  :ensure t
  :config
  (evil-leader/set-key
    "p f"   'projectile-find-file
    "p F"   'projectile-find-file-in-known-projects
    "p o"   'projectile-multi-occur
    "x r"   'projectile-replace
    "x R"   'projectile-regenerate-tags
    "p t"   'projectile-find-tag
    "p p"   'projectile-switch-project)

  (require 'projectile)
  (setq projectile-globally-ignored-files
    (append '("*.class" "*.o" "*.so" "*.elc" "*.jar" "*.png" "*.jpg" "*.jpeg" "*.gif")
            projectile-globally-ignored-files))
  (setq projectile-globally-ignored-directories
    (append '("target")
    projectile-globally-ignored-directories))

  (projectile-global-mode)) ;; any directory can be a project
#+END_SRC

** Ag

#+BEGIN_SRC emacs-lisp
(use-package ag
  :ensure t
  :config
  (evil-leader/set-key "a" 'ag)
  :init
  (setq ag-highlight-search t)
  (setq ag-reuse-buffers t))
#+END_SRC

** Desktop & Eyebrowse for workflow management

Saving Emacs sessions with destkop.

#+BEGIN_SRC emacs-lisp
(use-package desktop
  :init
  (setq desktop-path '("~/.emacs.d/"))
  (setq desktop-dirname "~/.emacs.d/")
  (setq desktop-auto-save-timeout 10)
  :config
  (desktop-save-mode))
#+END_SRC

#+BEGIN_QUOTE
  eyebrowse is a global minor mode for Emacs that allows you to manage your
  window configurations in a simple manner, just like tiling window managers
  like i3wm with their workspaces do. It displays their current state in the
  modeline by default. The behaviour is modeled after ranger, a file manager
  written in Python.

  -- https://github.com/bbatsov/projectile
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(use-package eyebrowse
  :diminish eyebrowse-mode
  :ensure t
  :config
  (define-key evil-motion-state-map (kbd "gR") 'eyebrowse-rename-window-config)
  (eyebrowse-mode)
  (eyebrowse-setup-opinionated-keys))
#+END_SRC
