#+TITLE: tao-visual

* Graphical settings

Editor settings related to visual style or visual aids.

** General

#+BEGIN_SRC emacs-lisp
(setq ring-bell-function 'ignore)
#+END_SRC

** Fonts

#+BEGIN_SRC emacs-lisp
(if (member "DejaVu Sans Mono" (font-family-list))
    (set-face-attribute
     'default nil :font "DejaVu Sans Mono 14"))
#+END_SRC

** Theme

*** Qsimpleq

Bright, nice on the eye visual theme.

#+BEGIN_SRC emacs-lisp
;; treat qsimpleq theme as safe
(setq custom-safe-themes (quote ("48441785d77807dce4e71b065f17504fbdfb6cbcd475523d20da4f1a14fbddac" qsimpleq-theme)))
(add-to-list 'custom-theme-load-path (expand-file-name "themes" tao-dir))
(load-theme 'qsimpleq)
#+END_SRC

** Fill column indicator

#+BEGIN_QUOTE
  Many modern editors and IDEs can graphically indicate the location of
  the fill column by drawing a thin line (in design parlance, a "rule") down
  the length of the editing window. Fill-column-indicator implements this
  facility in Emacs.

  -- [[https://github.com/alpaker/Fill-Column-Indicator][https://github.com/alpaker/Fill-Column-Indicator]]
#+END_QUOTE

I really do care about text/code line width, so:

#+BEGIN_SRC emacs-lisp
(bundle! fill-column-indicator
  (setq fci-rule-column 90) ;; 90 is really ok
  (add-hook 'text-mode-hook 'fci-mode)
  (add-hook 'prog-mode-hook 'fci-mode))
#+END_SRC

** rainbow delimiters

Rainbow delimiters is like rainbow parentheses, but less intrusive and generally
better.

#+BEGIN_QUOTE
  Rainbow Delimiters is a "rainbow parentheses"-like mode which highlights
  parentheses, brackets, and braces according to their depth. Each successive
  level is highlighted in a different color. This makes it easy to spot
  matching delimiters, orient yourself in the code, and tell which statements
  are at a given depth.

  -- [[https://github.com/jlr/rainbow-delimiters][https://github.com/jlr/rainbow-delimiters]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(bundle rainbow-delimiters
 (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))
#+END_SRC

** diminish

Modeline gets really messy with lots of packages installed. [[https://github.com/emacsmirror/diminish][diminish]] fixes
that by removing predefined minor modes from it.

#+BEGIN_SRC emacs-lisp
(bundle! diminish
  (eval-after-load "flyspell"
    '(diminish 'flyspell-mode))
  (eval-after-load "flycheck"
    '(diminish 'flycheck-mode))
  (diminish 'abbrev-mode)
  (eval-after-load "auto-revert-mode"
    '(diminish 'auto-revert-mode))
  (eval-after-load "company"
    '(diminish 'company-mode))
  (eval-after-load "helm"
    '(diminish 'helm-mode))
  (eval-after-load "projectile"
    '(diminish 'projectile-mode))
  (eval-after-load "smartparens"
    '(diminish 'smartparens-mode))
  (diminish 'whitespace-mode)
  (diminish 'undo-tree-mode))
#+END_SRC
